apiVersion: v1
kind: Service
metadata:
    name: waheedahmedazurevotingappredis
spec:
    type: LoadBalancer
    ports:
    - port: 8080
    selector:
        app: waheedahmedazurevotingappredis
